spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assesment
    username: postgres
    password: bony
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: alex987morgan@gmail.com
    password: dgrtuuuzqmpozwgn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecretKeyForLanguageAssessmentApp12345678901234567890}
  expiration: 86400000 # 24 hours

# App Configuration
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  email:
    from: ${FROM_EMAIL:noreply@language-assessment.com}

# M-Pesa Configuration
mpesa:
  consumer:
    key: ${MPESA_CONSUMER_KEY:your_consumer_key}
    secret: ${MPESA_CONSUMER_SECRET:your_consumer_secret}
  shortcode: ${MPESA_SHORTCODE:174379}
  passkey: ${MPESA_PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}
  callback:
    url: ${MPESA_CALLBACK_URL:https://yourdomain.com/api/mpesa/callback}

# Logging Configuration
logging:
  level:
    com.tritva.assessment: DEBUG
    org.springframework.security: DEBUG